name: Submit to AMO

on:
  push:
    branches:   
      - master

jobs:
  amo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install web-ext-submit
        run: | 
         npm install web-ext-submit --global
      - name: Submit to AMO
        run: |
          web-ext-submit --api-key=${{ secrets.AMO_API }} --api-secret=${{ secrets.AMO_SECRET }} --channel=listed --ignore-files manifest_chrome.json README.md
      
